version: '3'

services:
  interface-service:
    image: rubythalib/interface-service:latest
    container_name: interface-service
    ports:
      - "8000:8000"
    environment:
      KAFKA_SERVER: kafka:9092
      RESTAURANT_SERVICE_URL: "http://restaurant-service:8001"
      ORDER_SERVICE_URL: "http://order-service:8001"
    depends_on:
      - kafka
      - database-service
      - order-service

  order-service:
    image: rubythalib/order-service:latest
    container_name: order-service
    ports:
      - "8001:8001"
    environment:
      KAFKA_SERVER: kafka:9092
      DATABASE_SERVICE_URL: "http://database-service:7000"
    depends_on:
      - kafka
      - database-service
  
  restaurant-service:
    image: rubythalib/restaurant-service:latest
    container_name: restaurant-service
    ports:
      - "8002:8001"
    environment:
      KAFKA_SERVER: kafka:9092
      DATABASE_SERVICE_URL: "http://database-service:7000"
    depends_on:
      - kafka
      - database-service

  payment-service:
    image: rubythalib/payment-service:latest
    container_name: payment-service
    environment:
      KAFKA_SERVER: kafka:9092
    depends_on:
      - kafka

  driver-service:
    image: rubythalib/driver-service:latest
    container_name: driver-service
    environment:
      KAFKA_SERVER: kafka:9092
    depends_on:
      - kafka

  database-service:
    image: rubythalib/database-service:latest
    container_name: database-service
    ports:
      - "7000:7000"
    environment:
      KAFKA_SERVER: kafka:9092
      MONGO_SERVER: mongo:27017
    depends_on:
      - kafka
      - mongo
      - payment-service
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # Set to "true" if you want auto topic creation
    depends_on:
      - zookeeper

