version: '3'

services:
  interface-service:
    image: rubythalib/interface-service:latest
    container_name: interface-service
    ports:
      - "8000:8000"
    environment:
      REDIS_SERVER: redis
      RESTAURANT_SERVICE_URL: "http://restaurant-service:8001"
      ORDER_SERVICE_URL: "http://order-service:8001"
    depends_on:
      - redis
      - database-service
      - order-service

  order-service:
    image: rubythalib/order-service:latest
    container_name: order-service
    ports:
      - "8001:8001"
    environment:
      REDIS_SERVER: redis
      DATABASE_SERVICE_URL: "http://database-service:7000"
    depends_on:
      - redis
      - database-service
  
  restaurant-service:
    image: rubythalib/restaurant-service:latest
    container_name: restaurant-service
    ports:
      - "8002:8001"
    environment:
      REDIS_SERVER: redis
      DATABASE_SERVICE_URL: "http://database-service:7000"
    depends_on:
      - redis
      - database-service

  payment-service:
    image: rubythalib/payment-service:latest
    container_name: payment-service
    environment:
      REDIS_SERVER: redis
    depends_on:
      - redis

  driver-service:
    image: rubythalib/driver-service:latest
    container_name: driver-service
    environment:
      REDIS_SERVER: redis
    depends_on:
      - redis

  database-service:
    image: rubythalib/database-service:latest
    container_name: database-service
    ports:
      - "7000:7000"
    environment:
      REDIS_SERVER: redis
      MONGO_SERVER: mongo:27017
    depends_on:
      - redis
      - mongo
      - payment-service
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
